// Generated from C:/Users/user/Desktop/financial-derivatives research.md.
// The source report only accepts official Binance, Binance Academy, and Binance developer domains.

export type FaqPriority = "P0" | "P1" | "P2" | "P3";
export type FaqSource = "FAQ" | "FAQ Index" | "Developer Docs" | "Academy/Blog" | "Announcement" | "Live Data" | "Official Page";

export interface FaqEntry {
  id: string;
  title: string;
  url: string;
  product: string;
  productArea: string;
  subcategory: string;
  section: string;
  pageType: string;
  source: FaqSource;
  priority: FaqPriority;
  confidence: string;
  keyTopics: string[];
  supportUseCases: string[];
}

export const faqCatalog: FaqEntry[] = [
  {
    "id": "011-binance-coin-margined-futures-contract-specifications",
    "title": "Binance COIN-Margined Futures Contract Specifications",
    "url": "https://www.binance.com/en/support/faq/binance-coin-margined-futures-contract-specifications-a4470430e3164c13932be8967961aede",
    "product": "COIN-M Futures",
    "productArea": "COIN-M",
    "subcategory": "Specifications",
    "section": "A. Futures Core / COIN-M Futures",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "inverse",
      "contract multiplier",
      "perpetual/quarterly/bi-quarterly",
      "8h funding"
    ],
    "supportUseCases": [
      "COIN-M specs"
    ]
  },
  {
    "id": "014-how-to-calculate-liquidation-price-of-coin-m-futures-contracts",
    "title": "How to Calculate Liquidation Price of Coin-M Futures Contracts",
    "url": "https://www.binance.com/en/support/faq/how-to-calculate-liquidation-price-of-coin-m-futures-contracts-ceccfcfb4e3a45e3b48b0b1bb1a8ae46",
    "product": "COIN-M Futures",
    "productArea": "COIN-M",
    "subcategory": "Liquidation",
    "section": "A. Futures Core / COIN-M Futures",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "WB",
      "TMM1",
      "cross/isolated",
      "maintenance amount"
    ],
    "supportUseCases": [
      "COIN-M liquidation math"
    ]
  },
  {
    "id": "015-leverage-and-margin-in-coin-margined-contracts",
    "title": "Leverage and Margin in Coin-Margined Contracts",
    "url": "https://www.binance.com/en/support/faq/leverage-and-margin-in-coin-margined-futures-contracts-be2c7d9d95b04a7e8044ed02dd7dfe5c",
    "product": "COIN-M Futures",
    "productArea": "COIN-M Futures",
    "subcategory": "COIN-M Futures",
    "section": "A. Futures Core / COIN-M Futures",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "013-mark-price-and-price-index-of-coin-margined-contracts",
    "title": "Mark Price and Price Index of COIN-Margined Contracts",
    "url": "https://www.binance.com/en/support/faq/mark-price-and-price-index-of-coin-margined-contracts-fff6ec1b3f5845d19f1fb924644a0877",
    "product": "COIN-M Futures",
    "productArea": "COIN-M",
    "subcategory": "Mark/Index Price",
    "section": "A. Futures Core / COIN-M Futures",
    "pageType": "FAQ",
    "source": "FAQ Index",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "Median formula",
      "perpetual & quarterly formulas",
      "expiry-time formula"
    ],
    "supportUseCases": [
      "COIN-M mark price questions"
    ]
  },
  {
    "id": "012-a-quick-guide-to-coin-margined-quarterly-contracts",
    "title": "A Quick Guide to Coin-Margined Quarterly Contracts",
    "url": "https://www.binance.com/en/support/faq/a-quick-guide-to-coin-margined-quarterly-contracts-d33f37e2c7fe4da3b35ffc904e8fbab5",
    "product": "COIN-M Futures",
    "productArea": "COIN-M Futures",
    "subcategory": "COIN-M Futures",
    "section": "A. Futures Core / COIN-M Futures",
    "pageType": "FAQ (formulas)",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "016-asset-conversion-function-coin-m-wallet",
    "title": "Asset Conversion Function (COIN-M Wallet)",
    "url": "https://www.binance.com/en/support/faq/how-to-use-asset-conversion-function-c266e860664a494b86517ee8608ae7b8",
    "product": "COIN-M Futures",
    "productArea": "COIN-M Futures",
    "subcategory": "COIN-M Futures",
    "section": "A. Futures Core / COIN-M Futures",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "067-position-limit-adjustment-extended-to-coin-m-announce",
    "title": "Position Limit Adjustment Extended to COIN-M (announce)",
    "url": "https://www.binance.com/en/support/announcement/binance-futures-extends-the-position-limit-adjustment-feature-to-coin-m-contracts-6f64e15065774ce9a1914e5f8845f761",
    "product": "COIN-M Futures",
    "productArea": "COIN-M Futures",
    "subcategory": "Risk Controls & Trading Rules",
    "section": "A. Futures Core / Risk Controls & Trading Rules",
    "pageType": "FAQ",
    "source": "Announcement",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "106-binance-copy-trading-rules",
    "title": "Binance Copy Trading Rules",
    "url": "https://www.binance.com/en/support/faq/binance-copy-trading-rules-30f1e3a2835345e0b8ffc87f261a8256",
    "product": "Copy Trading",
    "productArea": "Copy Trading",
    "subcategory": "Copy Trading",
    "section": "D. Bots / Copy Trading",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "100-faq-on-binance-futures-copy-trading",
    "title": "FAQ on Binance Futures Copy Trading",
    "url": "https://www.binance.com/en/support/faq/frequently-asked-questions-on-binance-futures-copy-trading-6ed0995daf0b42d5816beaf1e31ca09d",
    "product": "Copy Trading",
    "productArea": "Copy Trading",
    "subcategory": "Copy Trading",
    "section": "D. Bots / Copy Trading",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "099-how-to-use-copy-trading-on-binance-futures",
    "title": "How to Use Copy Trading on Binance Futures",
    "url": "https://www.binance.com/en/support/faq/how-to-use-copy-trading-on-binance-futures-0b3a91eea664402f812fe41358c8a206",
    "product": "Copy Trading",
    "productArea": "Copy Trading",
    "subcategory": "Copy Trading",
    "section": "D. Bots / Copy Trading",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "107-copy-loss-protection-vouchers-futures",
    "title": "Copy Loss Protection Vouchers (Futures)",
    "url": "https://www.binance.com/en/support/faq/how-to-use-copy-loss-protection-vouchers-futures-7707e68163094e18b5d308a42d69ea4f",
    "product": "Copy Trading",
    "productArea": "Copy Trading",
    "subcategory": "Copy Trading",
    "section": "D. Bots / Copy Trading",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "104-copy-trading-service-list",
    "title": "Copy Trading Service List",
    "url": "https://www.binance.com/en/support/faq/binance-futures-copy-trading-service-list-d898460abbd14bd8aab54954ca0d606a",
    "product": "Copy Trading",
    "productArea": "Copy Trading",
    "subcategory": "Copy Trading",
    "section": "D. Bots / Copy Trading",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "101-how-to-lead-trade-on-binance-futures",
    "title": "How to Lead Trade on Binance Futures",
    "url": "https://www.binance.com/en/support/faq/how-to-lead-trade-on-binance-futures-6acfb4c1f50c4db1b9e915181ff31a4c",
    "product": "Copy Trading",
    "productArea": "Copy Trading",
    "subcategory": "Copy Trading",
    "section": "D. Bots / Copy Trading",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "103-lead-trader-growth-plan",
    "title": "Lead Trader Growth Plan",
    "url": "https://www.binance.com/en/support/faq/binance-futures-copy-trading-lead-trader-growth-plan-3160c961b2734d1cbb5342d1e86c6cdb",
    "product": "Copy Trading",
    "productArea": "Copy Trading",
    "subcategory": "Copy Trading",
    "section": "D. Bots / Copy Trading",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "102-lead-trader-guide",
    "title": "Lead Trader Guide",
    "url": "https://www.binance.com/en/support/faq/detail/552c6a26060d4f7fadf7a6d25c829d85",
    "product": "Copy Trading",
    "productArea": "Copy Trading",
    "subcategory": "Copy Trading",
    "section": "D. Bots / Copy Trading",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "105-mock-copy-trading",
    "title": "Mock Copy Trading",
    "url": "https://www.binance.com/en/support/faq/how-to-use-mock-copy-trading-on-binance-futures-d4badb1bcd6347e6a8f701b9cde08f0b",
    "product": "Copy Trading",
    "productArea": "Copy Trading",
    "subcategory": "Copy Trading",
    "section": "D. Bots / Copy Trading",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "123-common-definition-usds-m-futures",
    "title": "Common Definition (USDS-M Futures)",
    "url": "https://developers.binance.com/docs/derivatives/usds-margined-futures/common-definition",
    "product": "Developer/API",
    "productArea": "Futures API",
    "subcategory": "Reference",
    "section": "Futures API / Reference",
    "pageType": "Dev docs",
    "source": "Developer Docs",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "GTC",
      "IOC",
      "FOK",
      "GTX",
      "GTD",
      "RPI",
      "CONTRACT_PRICE",
      "MARK_PRICE workingType"
    ],
    "supportUseCases": [
      "Order params reference"
    ]
  },
  {
    "id": "125-derivatives-change-log",
    "title": "Derivatives Change Log",
    "url": "https://developers.binance.com/docs/derivatives/change-log",
    "product": "Developer/API",
    "productArea": "All Derivatives",
    "subcategory": "Change log",
    "section": "All Derivatives / Change log",
    "pageType": "Dev docs",
    "source": "Developer Docs",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "2025-12-09 algo migration",
      "2025-10-23 priceMatch removal",
      "2026-04-23 legacy WS decommission"
    ],
    "supportUseCases": [
      "Breaking-change watcher"
    ]
  },
  {
    "id": "122-self-trade-prevention-stp-faq-api",
    "title": "Self Trade Prevention (STP) FAQ - API",
    "url": "https://developers.binance.com/docs/derivatives/usds-margined-futures/faq/stp-faq",
    "product": "Developer/API",
    "productArea": "Futures API",
    "subcategory": "FAQ",
    "section": "Futures API / FAQ",
    "pageType": "Dev FAQ",
    "source": "Developer Docs",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "STP",
      "tradeGroupId",
      "EXPIRED_IN_MATCH"
    ],
    "supportUseCases": [
      "API-side STP help"
    ]
  },
  {
    "id": "124-usds-m-futures-error-codes",
    "title": "USDS-M Futures Error Codes",
    "url": "https://developers.binance.com/docs/derivatives/usds-margined-futures/error-code",
    "product": "Developer/API",
    "productArea": "Futures API",
    "subcategory": "Errors",
    "section": "Futures API / Errors",
    "pageType": "Dev docs",
    "source": "Developer Docs",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "-4120 STOP_ORDER_SWITCH_ALGO",
      "error code mapping"
    ],
    "supportUseCases": [
      "Order rejection triage"
    ]
  },
  {
    "id": "093-binance-portfolio-margin-api",
    "title": "Binance Portfolio Margin API",
    "url": "https://www.binance.com/en/support/faq/binance-portfolio-margin-api-ccf04078d7774d479f11ae15c4f56081",
    "product": "Developer/API",
    "productArea": "Portfolio Margin",
    "subcategory": "Portfolio Margin",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "086-multi-assets-mode-api-interface",
    "title": "Multi-Assets Mode API Interface",
    "url": "https://www.binance.com/en/support/faq/binance-multi-assets-mode-api-interface-6bdfbdd18c2a4140b24e0caa306c0df6",
    "product": "Developer/API",
    "productArea": "Multi-Assets Mode",
    "subcategory": "Multi-Assets Mode",
    "section": "C. Portfolio / Advanced Account Modes / Multi-Assets Mode",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "020-a-beginner-s-guide-to-futures-trading",
    "title": "A Beginner's Guide to Futures Trading",
    "url": "https://www.binance.com/en/support/faq/a-beginner-s-guide-to-futures-trading-360039304272",
    "product": "Futures Core",
    "productArea": "USDS-M / COIN-M",
    "subcategory": "Onboarding",
    "section": "A. Futures Core / Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "long/short",
      "ROI%",
      "unrealized PNL",
      "leverage",
      "margin"
    ],
    "supportUseCases": [
      "Beginner trading flow",
      "ROI calc"
    ]
  },
  {
    "id": "055-binance-futures-fee-structure-fee-calculations",
    "title": "Binance Futures Fee Structure & Fee Calculations",
    "url": "https://www.binance.com/en/support/faq/binance-futures-fee-structure-fee-calculations-360033544231",
    "product": "Futures Core",
    "productArea": "USDS-M / COIN-M",
    "subcategory": "Fees",
    "section": "A. Futures Core / Funding & Fees & PnL",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "VIP tiers",
      "BNB discount 10%",
      "taker/maker"
    ],
    "supportUseCases": [
      "Fee tier questions"
    ]
  },
  {
    "id": "038-binance-futures-liquidation-protocols",
    "title": "Binance Futures Liquidation Protocols",
    "url": "https://www.binance.com/en/support/faq/binance-futures-liquidation-protocols-360033525271",
    "product": "Futures Core",
    "productArea": "Generic Futures",
    "subcategory": "Liquidation",
    "section": "A. Futures Core / Liquidation, ADL, Insurance Fund",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "IOCO smart liquidation",
      "mark price as trigger",
      "liquidation clearance fee"
    ],
    "supportUseCases": [
      "Liquidation explanations"
    ]
  },
  {
    "id": "058-binance-futures-trading-quantitative-rules",
    "title": "Binance Futures Trading Quantitative Rules",
    "url": "https://www.binance.com/en/support/faq/binance-futures-trading-quantitative-rules-4f462ebe6ff445d4a170be7d9e897272",
    "product": "Futures Core",
    "productArea": "USDS-M",
    "subcategory": "Trading rules/Risk",
    "section": "A. Futures Core / Risk Controls & Trading Rules",
    "pageType": "Rule",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "UFR rule",
      "5-min/2h restrictions",
      "50-symbol limit",
      "reduce-only",
      "exemption whitelist"
    ],
    "supportUseCases": [
      "Quant-rule violation triage"
    ]
  },
  {
    "id": "059-binance-futures-trading-risk-control",
    "title": "Binance Futures Trading Risk Control",
    "url": "https://www.binance.com/en/support/faq/detail/f1afe9cbcd7a438492a0676e024f1897",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Risk Controls & Trading Rules",
    "section": "A. Futures Core / Risk Controls & Trading Rules",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "024-delivery-and-settlement-of-quarterly-futures",
    "title": "Delivery and Settlement of Quarterly Futures",
    "url": "https://www.binance.com/en/support/faq/delivery-and-settlement-of-quarterly-futures-a3401595e1734084959c61491bc0dbe3",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "section": "A. Futures Core / Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "046-how-to-adjust-contract-leverage",
    "title": "How to Adjust Contract Leverage",
    "url": "https://www.binance.com/en/support/faq/how-to-adjust-contract-leverage-360034946672",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Leverage",
    "section": "A. Futures Core / Margin / Leverage",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "056-how-to-calculate-profit-and-loss-for-futures-contracts",
    "title": "How to Calculate Profit and Loss for Futures Contracts",
    "url": "https://www.binance.com/en/support/faq/how-to-calculate-profit-and-loss-for-futures-contracts-3a55a23768cb416fb404f06ffedde4b2",
    "product": "Futures Core",
    "productArea": "USDS-M / COIN-M",
    "subcategory": "PnL",
    "section": "A. Futures Core / Funding & Fees & PnL",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "USDS-M PNL",
      "COIN-M PNL",
      "ROI%"
    ],
    "supportUseCases": [
      "PnL math"
    ]
  },
  {
    "id": "060-how-to-enable-the-price-protection-function",
    "title": "How to Enable the Price Protection Function",
    "url": "https://www.binance.com/en/support/faq/how-to-enable-the-price-protection-function-2b9dc811ce7340469357867122b975dc",
    "product": "Futures Core",
    "productArea": "USDS-M / COIN-M",
    "subcategory": "Trading rules/Risk",
    "section": "A. Futures Core / Risk Controls & Trading Rules",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "Last vs Mark threshold",
      "blocks TP/SL",
      "API exempt"
    ],
    "supportUseCases": [
      "Price Protection questions"
    ]
  },
  {
    "id": "037-how-to-open-or-close-position-in-hedge-mode",
    "title": "How to Open or Close Position in Hedge Mode",
    "url": "https://www.binance.com/en/support/faq/how-to-open-or-close-position-in-hedge-mode-360041515312",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Position modes",
    "section": "A. Futures Core / Position modes",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "027-how-to-place-stop-loss-take-profit-orders",
    "title": "How to Place Stop Loss / Take Profit Orders",
    "url": "https://www.binance.com/en/support/faq/how-to-place-stop-loss-and-take-profit-orders-on-binance-futures-360040016512",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "section": "A. Futures Core / Orders (limit, market, stop, TP/SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "053-introduction-to-binance-futures-funding-rates",
    "title": "Introduction to Binance Futures Funding Rates",
    "url": "https://www.binance.com/en/support/faq/introduction-to-binance-futures-funding-rates-360033525031",
    "product": "Futures Core",
    "productArea": "USDS-M / COIN-M (Perp)",
    "subcategory": "Funding",
    "section": "A. Futures Core / Funding & Fees & PnL",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "8h interval",
      "interest 0.03% daily",
      "Premium Index",
      "Impact Margin Notional",
      "cap/floor"
    ],
    "supportUseCases": [
      "Funding mechanics"
    ]
  },
  {
    "id": "042-introduction-to-futures-insurance-funds",
    "title": "Introduction to Futures Insurance Funds",
    "url": "https://www.binance.com/en/support/faq/introduction-to-futures-insurance-funds-360033525371",
    "product": "Futures Core",
    "productArea": "Generic Futures",
    "subcategory": "Risk/Insurance",
    "section": "A. Futures Core / Liquidation, ADL, Insurance Fund",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "bankrupt position",
      "99.9% calibration",
      "fund composition"
    ],
    "supportUseCases": [
      "Insurance fund questions"
    ]
  },
  {
    "id": "029-limit-tp-sl-strategy-otoco-faq",
    "title": "Limit TP/SL (Strategy / OTOCO) FAQ",
    "url": "https://www.binance.com/en/support/faq/what-are-limit-tp-sl-orders-strategy-orders-and-frequently-asked-questions-e1ee1738141c49718550fa9061be4bf3",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "section": "A. Futures Core / Orders (limit, market, stop, TP/SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "035-summary-of-failed-orders",
    "title": "Summary of Failed Orders",
    "url": "https://www.binance.com/en/support/faq/summary-of-failed-orders-in-binance-futures-360039707291",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "section": "A. Futures Core / Orders (limit, market, stop, TP/SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "047-switch-cross-isolated-margin",
    "title": "Switch Cross / Isolated Margin",
    "url": "https://www.binance.com/en/support/faq/how-to-switch-between-the-cross-margin-and-isolated-margin-modes-360038075852",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Leverage",
    "section": "A. Futures Core / Margin / Leverage",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "025-types-of-order-on-binance-futures",
    "title": "Types of Order on Binance Futures",
    "url": "https://www.binance.com/en/support/faq/types-of-order-on-binance-futures-360033779452",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "section": "A. Futures Core / Orders (limit, market, stop, TP/SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "052-updates-on-leverage-rules-for-new-accounts-announce",
    "title": "Updates on Leverage Rules for New Accounts (announce)",
    "url": "https://www.binance.com/en/support/announcement/updates-on-rules-of-binance-futures-leverage-for-new-accounts-2021-07-27-d6457e23eb2e42f2b9c3ce44f46f9a6d",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Leverage",
    "section": "A. Futures Core / Margin / Leverage",
    "pageType": "FAQ",
    "source": "Announcement",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "021-what-are-perpetual-futures-and-quarterly-futures",
    "title": "What Are Perpetual Futures and Quarterly Futures",
    "url": "https://www.binance.com/en/support/faq/what-are-perpetual-futures-and-quarterly-futures-d2a1afd5f829455c9ded23f0ca561a40",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "section": "A. Futures Core / Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "054-what-fees-are-generated-in-binance-futures-trading",
    "title": "What Fees are Generated in Binance Futures Trading",
    "url": "https://www.binance.com/en/support/faq/what-fees-are-generated-in-binance-futures-trading-98488a516eb84e3eb34605683dffd554",
    "product": "Futures Core",
    "productArea": "USDS-M / COIN-M",
    "subcategory": "Fees",
    "section": "A. Futures Core / Funding & Fees & PnL",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "commission",
      "funding",
      "insurance clearance"
    ],
    "supportUseCases": [
      "Fee questions"
    ]
  },
  {
    "id": "028-what-is-a-trailing-stop-order",
    "title": "What Is a Trailing Stop Order",
    "url": "https://www.binance.com/en/support/faq/what-is-a-trailing-stop-order-360042299292",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "section": "A. Futures Core / Orders (limit, market, stop, TP/SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "040-what-is-auto-deleveraging-adl-and-how-does-it-work",
    "title": "What Is Auto-Deleveraging (ADL) and How Does It Work",
    "url": "https://www.binance.com/en/support/faq/what-is-auto-deleveraging-adl-and-how-does-it-work-360033525471",
    "product": "Futures Core",
    "productArea": "Generic Futures",
    "subcategory": "Risk/ADL",
    "section": "A. Futures Core / Liquidation, ADL, Insurance Fund",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "ADL queue",
      "bankruptcy price",
      "ADL indicator"
    ],
    "supportUseCases": [
      "ADL questions"
    ]
  },
  {
    "id": "036-what-is-hedge-mode-and-how-to-use-it",
    "title": "What Is Hedge Mode and How to Use It",
    "url": "https://www.binance.com/en/support/faq/what-is-hedge-mode-and-how-to-use-it-360041513552",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Position modes",
    "section": "A. Futures Core / Position modes",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "063-what-is-self-trade-prevention-stp",
    "title": "What Is Self Trade Prevention (STP)",
    "url": "https://www.binance.com/en/support/faq/what-is-self-trade-prevention-stp-0941126f6413485b9a3df964a9aa2306",
    "product": "Futures Core",
    "productArea": "Generic Futures",
    "subcategory": "Trading rules/Risk",
    "section": "A. Futures Core / Risk Controls & Trading Rules",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "NONE",
      "EXPIRE_TAKER",
      "EXPIRE_MAKER",
      "EXPIRE_BOTH",
      "tradeGroupId",
      "selfTradePreventionMode"
    ],
    "supportUseCases": [
      "STP/wash trade questions"
    ]
  },
  {
    "id": "026-what-is-stop-order",
    "title": "What Is Stop Order",
    "url": "https://www.binance.com/en/support/faq/what-is-stop-order-360036351051",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "section": "A. Futures Core / Orders (limit, market, stop, TP/SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "061-what-is-the-cooling-period-function-and-how-to-use-it",
    "title": "What Is the Cooling Period Function and How to Use It",
    "url": "https://www.binance.com/en/support/faq/what-is-the-cooling-period-function-and-how-to-use-it-ad7fd07f63a64954a6d6e9257d16adcc",
    "product": "Futures Core",
    "productArea": "USDS-M / COIN-M",
    "subcategory": "Risk",
    "section": "A. Futures Core / Risk Controls & Trading Rules",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "1d/1w/1m/indefinite",
      "reduce-only allowed"
    ],
    "supportUseCases": [
      "Cooling period feature"
    ]
  },
  {
    "id": "048-adjust-margin-balance-cross-isolated",
    "title": "Adjust Margin Balance Cross/Isolated",
    "url": "https://www.binance.com/en/support/faq/how-to-adjust-margin-balance-in-cross-isolated-margin-mode-360038447311",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Leverage",
    "section": "A. Futures Core / Margin / Leverage",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "041-auto-deleveraging-guarantee-on-btc-eth-announcement",
    "title": "Auto Deleveraging Guarantee on BTC, ETH ... (announcement)",
    "url": "https://www.binance.com/en/support/announcement/detail/8ca05ebf2dcd4e2cbf5a7d2a313ab492",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Liquidation, ADL, Insurance Fund",
    "section": "A. Futures Core / Liquidation, ADL, Insurance Fund",
    "pageType": "FAQ",
    "source": "Announcement",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "031-bbo-orders",
    "title": "BBO Orders",
    "url": "https://www.binance.com/en/support/faq/understanding-and-using-bbo-orders-on-binance-futures-7f93c89ef09042678cfa73e8a28612e8",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "section": "A. Futures Core / Orders (limit, market, stop, TP/SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "057-close-all-positions-pnl-based-on-last-price",
    "title": "Close-All Positions & PnL Based on Last Price",
    "url": "https://www.binance.com/en/support/faq/how-to-use-close-all-positions-function-and-profit-and-loss-calculations-based-on-last-price-ef56e7d1f00948f0b0da68fdf8b82d13",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Funding & Fees & PnL",
    "section": "A. Futures Core / Funding & Fees & PnL",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "032-conditional-orders",
    "title": "Conditional Orders",
    "url": "https://www.binance.com/en/support/faq/what-are-conditional-orders-998e63d2587d4e2fb894b1615de3b288",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "section": "A. Futures Core / Orders (limit, market, stop, TP/SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "051-cost-required-to-open-a-position",
    "title": "Cost Required to Open a Position",
    "url": "https://www.binance.com/en/support/faq/how-to-calculate-cost-required-to-open-a-position-in-perpetual-futures-contracts-87fa7ee33b574f7084d42bd2ce2e463b",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Leverage",
    "section": "A. Futures Core / Margin / Leverage",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "126-crypto-derivatives-faq-hub",
    "title": "Crypto Derivatives FAQ Hub",
    "url": "https://www.binance.com/en/support/faq/crypto-derivatives?c=4",
    "product": "Futures Core",
    "productArea": "All Derivatives",
    "subcategory": "Hub",
    "section": "All Derivatives / Hub",
    "pageType": "FAQ Index",
    "source": "FAQ Index",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [
      "futures",
      "options",
      "portfolio margin",
      "copy trading",
      "BFUSD"
    ],
    "supportUseCases": [
      "Coverage assurance"
    ]
  },
  {
    "id": "023-delisting-of-futures-contracts",
    "title": "Delisting of Futures Contracts",
    "url": "https://www.binance.com/en/support/faq/delisting-of-futures-contracts-dd60dfbf654d4055aa6b217ea6d5ddba",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "section": "A. Futures Core / Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "022-differences-between-perpetual-traditional-futures",
    "title": "Differences Between Perpetual & Traditional Futures",
    "url": "https://www.binance.com/en/support/faq/differences-between-perpetual-contract-and-traditional-futures-contract-360033524991",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "section": "A. Futures Core / Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "039-how-liquidation-works-in-futures-trading",
    "title": "How Liquidation Works in Futures Trading",
    "url": "https://www.binance.com/en/support/faq/how-liquidation-works-in-futures-trading-7ba80e1b406f40a0a140a84b3a10c387",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Liquidation, ADL, Insurance Fund",
    "section": "A. Futures Core / Liquidation, ADL, Insurance Fund",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "069-how-to-use-binance-futures-trading-interface",
    "title": "How to Use Binance Futures Trading Interface",
    "url": "https://www.binance.com/en/support/faq/how-to-use-binance-futures-trading-interface-8804f6d3e54e49dd941b74c1d8469008",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "How-tos",
    "section": "A. Futures Core / Interface / Tools / How-tos",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "070-how-to-use-the-binance-futures-calculator",
    "title": "How to Use the Binance Futures Calculator",
    "url": "https://www.binance.com/en/support/faq/how-to-use-the-binance-futures-calculator-360036498511",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "How-tos",
    "section": "A. Futures Core / Interface / Tools / How-tos",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "044-live-insurance-fund-balance-quarterly",
    "title": "Live: Insurance Fund Balance (Quarterly)",
    "url": "https://www.binance.com/en/futures/funding-history/quarterly/insurance-fund-history",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Liquidation, ADL, Insurance Fund",
    "section": "A. Futures Core / Liquidation, ADL, Insurance Fund",
    "pageType": "FAQ",
    "source": "Live Data",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "066-live-position-limit-adjustment-tool",
    "title": "Live: Position Limit Adjustment Tool",
    "url": "https://www.binance.com/en/futures/position/adjustment",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Risk Controls & Trading Rules",
    "section": "A. Futures Core / Risk Controls & Trading Rules",
    "pageType": "FAQ",
    "source": "Live Data",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "034-maker-post-only-tif-iceberg",
    "title": "Maker (Post Only), TIF, Iceberg",
    "url": "https://www.binance.com/en/support/faq/what-are-maker-post-only-order-time-in-force-order-and-iceberg-order-5d3fa5e5709f47e0b5f186b350da1655",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "section": "A. Futures Core / Orders (limit, market, stop, TP/SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "050-margin-requirement-on-binance-futures",
    "title": "Margin Requirement on Binance Futures",
    "url": "https://www.binance.com/en/support/faq/how-to-calculate-the-margin-requirement-on-binance-futures-trading-4f83b65d83654b5e933f85ef12bf769d",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Leverage",
    "section": "A. Futures Core / Margin / Leverage",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "017-overview-of-binance-futures-products-and-features",
    "title": "Overview of Binance Futures Products and Features",
    "url": "https://www.binance.com/en/support/faq/an-overview-of-binance-futures-products-and-features-00bd4e5720bf4ffebfadb4b15e465a73",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "section": "A. Futures Core / Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "065-position-limit-adjustment",
    "title": "Position Limit Adjustment",
    "url": "https://www.binance.com/en/support/faq/your-guide-to-position-limit-adjustment-13163f41fe2b44af982e612dfe7e6709",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Risk Controls & Trading Rules",
    "section": "A. Futures Core / Risk Controls & Trading Rules",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "068-responsible-trading-hub",
    "title": "Responsible Trading Hub",
    "url": "https://www.binance.com/en/futures/responsible-trading",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Risk Controls & Trading Rules",
    "section": "A. Futures Core / Risk Controls & Trading Rules",
    "pageType": "FAQ",
    "source": "Official Page",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "064-stp-mandatory-rollout-announce-2024-12-10",
    "title": "STP Mandatory Rollout (announce 2024-12-10)",
    "url": "https://www.binance.com/en/support/announcement/binance-to-extend-the-self-trade-prevention-stp-function-to-all-binance-futures-users-2024-12-10-7803d494fa654f749fbc0a22a17372e3",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Risk Controls & Trading Rules",
    "section": "A. Futures Core / Risk Controls & Trading Rules",
    "pageType": "FAQ",
    "source": "Announcement",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "030-tp-sl-split-target-feature",
    "title": "TP/SL Split Target Feature",
    "url": "https://www.binance.com/en/support/faq/how-to-use-the-tp-sl-split-target-feature-on-binance-futures-717a9635f035490baffa564e2f19c7c1",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "section": "A. Futures Core / Orders (limit, market, stop, TP/SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "018-about-binance-futures",
    "title": "About Binance Futures",
    "url": "https://www.binance.com/en/support/faq/a2f2b768847c4e01a88aa07fab0a68d9",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "section": "A. Futures Core / Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "119-available-margin-total-balance-on-binance-futures-blog",
    "title": "Available, Margin, Total Balance on Binance Futures (Blog)",
    "url": "https://www.binance.com/en/blog/futures/what-is-the-available-balance-margin-balance-and-total-balance-on-binance-futures-457299340443288694",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "062-cooling-off-period-margin",
    "title": "Cooling-Off Period (Margin)",
    "url": "https://www.binance.com/en/support/faq/how-to-use-margin-cooling-off-period-9c660522f69547e8bcda1e7649c7b33b",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Risk Controls & Trading Rules",
    "section": "A. Futures Core / Risk Controls & Trading Rules",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "049-differences-between-isolated-cross-margin",
    "title": "Differences Between Isolated & Cross Margin",
    "url": "https://www.binance.com/en/support/faq/differences-between-isolated-margin-and-cross-margin-b4e9e6ad70934bd082e8e09e33e69513",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Leverage",
    "section": "A. Futures Core / Margin / Leverage",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "072-download-order-history-usds-m-coin-m",
    "title": "Download Order History (USDS-M / COIN-M)",
    "url": "https://www.binance.com/en/support/faq/how-to-download-my-order-history-for-usd%E2%93%A2-m-and-coin-m-futures-orders-e21b95dc590e4c13b8f8bdcc9bbc4f82",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "How-tos",
    "section": "A. Futures Core / Interface / Tools / How-tos",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "112-forced-liquidation-glossary",
    "title": "Forced Liquidation (glossary)",
    "url": "https://academy.binance.com/en/glossary/forced-liquidation",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "113-funding-fees-glossary",
    "title": "Funding Fees (glossary)",
    "url": "https://academy.binance.com/en/glossary/funding-fees",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "114-futures-contract-glossary",
    "title": "Futures Contract (glossary)",
    "url": "https://academy.binance.com/en/glossary/futures-contract",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "071-how-to-go-long-or-short-on-binance-futures",
    "title": "How to Go Long or Short on Binance Futures",
    "url": "https://www.binance.com/en/support/faq/how-to-go-long-or-short-on-binance-futures-489c90b44dbe454d85fc4cbdca10dcb1",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "How-tos",
    "section": "A. Futures Core / Interface / Tools / How-tos",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "116-liquidation-price-vs-bankruptcy-price-blog",
    "title": "Liquidation Price vs. Bankruptcy Price (Blog)",
    "url": "https://www.binance.com/en/blog/futures/3319141945917512624",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "120-managing-risks-with-hedge-mode-blog",
    "title": "Managing Risks With Hedge Mode (Blog)",
    "url": "https://www.binance.com/en/blog/futures/managing-risks-with-hedge-mode-in-crypto-futures-trading-3345275339961971082",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "045-margin-insurance-fund",
    "title": "Margin Insurance Fund",
    "url": "https://www.binance.com/en/margin/insurance-fund",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Liquidation, ADL, Insurance Fund",
    "section": "A. Futures Core / Liquidation, ADL, Insurance Fund",
    "pageType": "FAQ",
    "source": "Live Data",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "115-mark-price-vs-last-price-on-binance-futures-blog",
    "title": "Mark Price vs. Last Price on Binance Futures (Blog)",
    "url": "https://www.binance.com/en/blog/futures/5704082076024731087",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "033-scaled-orders",
    "title": "Scaled Orders",
    "url": "https://www.binance.com/en/support/faq/what-are-scaled-orders-and-how-do-they-work-109e5e36156d4c57a8ee29734f8bed3a",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "section": "A. Futures Core / Orders (limit, market, stop, TP/SL, trailing, conditional, scaled, BBO, post-only, TIF)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "019-what-are-cryptocurrency-futures",
    "title": "What Are Cryptocurrency Futures",
    "url": "https://www.binance.com/en/support/faq/what-are-cryptocurrency-futures-5b0f2f27760c4c439ba6f2de0716d8d0",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "section": "A. Futures Core / Cross-cutting Futures (overview, perpetual vs quarterly, delisting)",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "110-what-are-decentralized-derivatives",
    "title": "What Are Decentralized Derivatives?",
    "url": "https://academy.binance.com/en/articles/what-are-decentralized-derivatives-and-how-do-they-work-in-defi",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "109-what-are-funding-rates-in-crypto-markets",
    "title": "What Are Funding Rates in Crypto Markets?",
    "url": "https://academy.binance.com/en/articles/what-are-funding-rates-in-crypto-markets",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "108-what-are-perpetual-futures-contracts",
    "title": "What Are Perpetual Futures Contracts?",
    "url": "https://academy.binance.com/en/articles/what-are-perpetual-futures-contracts",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "121-what-can-you-expect-on-futures-expiration-day-blog",
    "title": "What Can You Expect on Futures Expiration Day (Blog)",
    "url": "https://www.binance.com/en/blog/futures/what-can-you-expect-on-futures-expiration-day-421499824684901024",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "118-what-is-futures-funding-rate-blog",
    "title": "What Is Futures Funding Rate (Blog)",
    "url": "https://www.binance.com/en/blog/futures/what-is-futures-funding-rate-and-why-it-matters-421499824684903247",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "117-what-is-liquidation-and-how-to-avoid-it-blog",
    "title": "What is Liquidation and How to Avoid It (Blog)",
    "url": "https://www.binance.com/en/blog/futures/crypto-futures-basics-what-is-liquidation-and-how-to-avoid-it-421499824684902466",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "111-what-is-open-interest",
    "title": "What Is Open Interest?",
    "url": "https://www.binance.com/en/academy/articles/what-is-open-interest",
    "product": "Futures Core",
    "productArea": "Futures Core",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Official Page",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "082-auto-exchange-in-multi-assets-mode",
    "title": "Auto-Exchange in Multi-Assets Mode",
    "url": "https://www.binance.com/en/support/faq/how-does-auto-exchange-work-in-the-multi-assets-mode-4108bab5e4784a8db0a6b8b88dcb1ccd",
    "product": "Multi-Assets Mode",
    "productArea": "Multi-Assets Mode",
    "subcategory": "Multi-Assets Mode",
    "section": "C. Portfolio / Advanced Account Modes / Multi-Assets Mode",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "083-calculate-margin-ratio-in-multi-assets-mode",
    "title": "Calculate Margin Ratio in Multi-Assets Mode",
    "url": "https://www.binance.com/en/support/faq/how-to-calculate-margin-ratio-in-the-multi-assets-mode-c983a9268cfa4e70a4916c276bb3b7bc",
    "product": "Multi-Assets Mode",
    "productArea": "Multi-Assets Mode",
    "subcategory": "Multi-Assets Mode",
    "section": "C. Portfolio / Advanced Account Modes / Multi-Assets Mode",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "085-faq-on-the-multi-assets-mode",
    "title": "FAQ on the Multi-Assets Mode",
    "url": "https://www.binance.com/en/support/faq/frequently-asked-questions-on-the-multi-assets-mode-f80415bea8124f6494566f23c0bf9c38",
    "product": "Multi-Assets Mode",
    "productArea": "Multi-Assets Mode",
    "subcategory": "Multi-Assets Mode",
    "section": "C. Portfolio / Advanced Account Modes / Multi-Assets Mode",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "079-what-is-multi-assets-mode",
    "title": "What Is Multi-Assets Mode",
    "url": "https://www.binance.com/en/support/faq/what-is-multi-assets-mode-and-which-assets-are-supported-29b45c485d664028b9ca1cdf90b24f6f",
    "product": "Multi-Assets Mode",
    "productArea": "Multi-Assets Mode",
    "subcategory": "Multi-Assets Mode",
    "section": "C. Portfolio / Advanced Account Modes / Multi-Assets Mode",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "080-benefits-of-multi-assets-mode",
    "title": "Benefits of Multi-Assets Mode",
    "url": "https://www.binance.com/en/support/faq/what-are-the-benefits-of-trading-usd%E2%93%A2-m-futures-in-the-multi-assets-mode-e18fac92defe4a118b4ed8804ae7d6fd",
    "product": "Multi-Assets Mode",
    "productArea": "Multi-Assets Mode",
    "subcategory": "Multi-Assets Mode",
    "section": "C. Portfolio / Advanced Account Modes / Multi-Assets Mode",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "084-check-asset-balance-in-multi-assets-mode",
    "title": "Check Asset Balance in Multi-Assets Mode",
    "url": "https://www.binance.com/en/support/faq/how-to-check-my-asset-balance-in-multi-assets-mode-5ff786bd0205475f84c506a057b22e79",
    "product": "Multi-Assets Mode",
    "productArea": "Multi-Assets Mode",
    "subcategory": "Multi-Assets Mode",
    "section": "C. Portfolio / Advanced Account Modes / Multi-Assets Mode",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "081-switch-single-asset-multi-assets",
    "title": "Switch Single-Asset / Multi-Assets",
    "url": "https://www.binance.com/en/support/faq/how-to-switch-between-single-asset-and-multi-assets-modes-de2681ac63714c7d84a685967f7c1a53",
    "product": "Multi-Assets Mode",
    "productArea": "Multi-Assets Mode",
    "subcategory": "Multi-Assets Mode",
    "section": "C. Portfolio / Advanced Account Modes / Multi-Assets Mode",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "074-binance-options-contract-specifications",
    "title": "Binance Options Contract Specifications",
    "url": "https://www.binance.com/en/support/faq/binance-options-contract-specifications-cdee5d43b70d4d2386980d41786a8533",
    "product": "Options",
    "productArea": "Options",
    "subcategory": "Specifications",
    "section": "B. Options",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "European-style",
      "BTC/ETH options",
      "expiry"
    ],
    "supportUseCases": [
      "Options reference"
    ]
  },
  {
    "id": "076-binance-options-auto-cancel-all-open-orders-kill-switch",
    "title": "Binance Options Auto-Cancel All Open Orders (Kill-Switch)",
    "url": "https://www.binance.com/en/support/faq/binance-options-auto-cancel-all-open-orders-kill-switch-17f031ed1a5642ab9c74a7b64b6864d2",
    "product": "Options",
    "productArea": "Options",
    "subcategory": "B. Options",
    "section": "B. Options",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "075-binance-options-market-maker-protection-mmp",
    "title": "Binance Options Market Maker Protection (MMP)",
    "url": "https://www.binance.com/en/support/faq/binance-options-market-maker-protection-mmp-0b81ad7d8ae54d3f8d29a1ce66764fa1",
    "product": "Options",
    "productArea": "Options",
    "subcategory": "B. Options",
    "section": "B. Options",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "077-options-faq-sub-index",
    "title": "Options FAQ (sub-index)",
    "url": "https://www.binance.com/en/support/faq/c-92",
    "product": "Options",
    "productArea": "Options",
    "subcategory": "B. Options",
    "section": "B. Options",
    "pageType": "FAQ",
    "source": "FAQ Index",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "078-what-are-options-contracts",
    "title": "What Are Options Contracts?",
    "url": "https://academy.binance.com/en/articles/what-are-options-contracts",
    "product": "Options",
    "productArea": "Options",
    "subcategory": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "section": "F. Academy explainers and Binance Blog (Futures sub-blog)",
    "pageType": "FAQ",
    "source": "Academy/Blog",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "089-binance-portfolio-margin-trading-rules",
    "title": "Binance Portfolio Margin Trading Rules",
    "url": "https://www.binance.com/en/support/faq/binance-portfolio-margin-trading-rules-174861644e7049aaa64845f1db2e4376",
    "product": "Portfolio Margin",
    "productArea": "Portfolio Margin",
    "subcategory": "Portfolio Margin",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "090-how-does-liquidation-work-in-the-binance-portfolio-margin-account",
    "title": "How Does Liquidation Work in the Binance Portfolio Margin Account",
    "url": "https://www.binance.com/en/support/faq/how-does-liquidation-work-in-the-binance-portfolio-margin-account-d0c3558829fa41eabeeaf3c32dbe1dad",
    "product": "Portfolio Margin",
    "productArea": "Portfolio Margin",
    "subcategory": "Liquidation",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "uniMMR",
      "liquidation"
    ],
    "supportUseCases": [
      "PM liquidation"
    ]
  },
  {
    "id": "088-how-to-activate-portfolio-margin-mode",
    "title": "How to Activate Portfolio Margin Mode",
    "url": "https://www.binance.com/en/support/faq/how-to-activate-the-portfolio-margin-mode-on-binance-7ee6b3f65d5a421491c0a5588223fd14",
    "product": "Portfolio Margin",
    "productArea": "Portfolio Margin",
    "subcategory": "Portfolio Margin",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "087-introduction-to-binance-portfolio-margin-mode",
    "title": "Introduction to Binance Portfolio Margin Mode",
    "url": "https://www.binance.com/en/support/faq/introduction-to-binance-portfolio-margin-mode-bddd924496d74ecd8820a6d95585ccee",
    "product": "Portfolio Margin",
    "productArea": "Portfolio Margin",
    "subcategory": "Overview",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "uniMMR",
      "cross-product margining"
    ],
    "supportUseCases": [
      "PM intro"
    ]
  },
  {
    "id": "092-pm-supported-collateral-rates",
    "title": "PM Supported Collateral & Rates",
    "url": "https://www.binance.com/en/support/faq/binance-portfolio-margin-mode-supported-collateral-and-rates-937b8e81d03f475c8d7a0d42ec381510",
    "product": "Portfolio Margin",
    "productArea": "Portfolio Margin",
    "subcategory": "Portfolio Margin",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "091-wallet-transfers-auto-fund-negative-balances-pm",
    "title": "Wallet Transfers, Auto Fund, Negative Balances (PM)",
    "url": "https://www.binance.com/en/support/faq/detail/c1df531bb7c44ea2a10919a74fd84f5e",
    "product": "Portfolio Margin",
    "productArea": "Portfolio Margin",
    "subcategory": "Portfolio Margin",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "095-faq-on-pm-pro-program",
    "title": "FAQ on PM Pro Program",
    "url": "https://www.binance.com/en/support/faq/frequently-asked-questions-on-binance-portfolio-margin-pro-program-446ce2c3357a449599c82436078b0e3b",
    "product": "Portfolio Margin",
    "productArea": "Portfolio Margin",
    "subcategory": "Portfolio Margin",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "097-liquidation-under-pm-pro",
    "title": "Liquidation Under PM Pro",
    "url": "https://www.binance.com/en/support/faq/how-does-liquidation-work-under-the-binance-portfolio-margin-pro-account-ff4b1ab6c27b4ed6b3ebe8e4ed1572f8",
    "product": "Portfolio Margin",
    "productArea": "Portfolio Margin",
    "subcategory": "Portfolio Margin",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "096-wallet-transfers-auto-fund-negative-balances-pm-pro",
    "title": "Wallet Transfers, Auto Fund, Negative Balances (PM Pro)",
    "url": "https://www.binance.com/en/support/faq/wallet-transfers-auto-fund-functions-and-negative-balances-in-portfolio-margin-pro-fa0c2866bbb84c1f98f32c606213332d",
    "product": "Portfolio Margin",
    "productArea": "Portfolio Margin",
    "subcategory": "Portfolio Margin",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "094-what-is-binance-pm-pro-program",
    "title": "What Is Binance PM Pro Program",
    "url": "https://www.binance.com/en/support/faq/detail/5054378212d240cca17ecd6006c11f23",
    "product": "Portfolio Margin",
    "productArea": "Portfolio Margin",
    "subcategory": "Portfolio Margin",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "098-tiered-negative-balance-thresholds-announce",
    "title": "Tiered Negative Balance Thresholds (announce)",
    "url": "https://www.binance.com/en/support/announcement/detail/8fb30aac8e484ef3b7ea6136150da60d",
    "product": "Portfolio Margin",
    "productArea": "Portfolio Margin",
    "subcategory": "Portfolio Margin",
    "section": "C. Portfolio / Advanced Account Modes / Portfolio Margin",
    "pageType": "FAQ",
    "source": "Announcement",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "007-how-to-calculate-liquidation-price-of-usds-m-futures-contracts",
    "title": "How to Calculate Liquidation Price of USDS-M Futures Contracts",
    "url": "https://www.binance.com/en/support/faq/how-to-calculate-liquidation-price-of-usd%E2%93%A2-m-futures-contracts-b3c689c1f50a44cabb3a84e663b81d93",
    "product": "USD-M Futures",
    "productArea": "USDS-M",
    "subcategory": "Liquidation",
    "section": "A. Futures Core / USDS-M Futures",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "WB",
      "TMM1",
      "UPNL1",
      "cumB/cumL/cumS",
      "MMR"
    ],
    "supportUseCases": [
      "USDS-M liquidation math"
    ]
  },
  {
    "id": "008-leverage-and-margin-of-usds-m-futures",
    "title": "Leverage and Margin of USDS-M Futures",
    "url": "https://www.binance.com/en/support/faq/leverage-and-margin-of-usd%E2%93%A2-m-futures-360033162192",
    "product": "USD-M Futures",
    "productArea": "USDS-M",
    "subcategory": "Margin/Leverage",
    "section": "A. Futures Core / USDS-M Futures",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "MMR brackets",
      "MM formula",
      "20x cap new account"
    ],
    "supportUseCases": [
      "Leverage tier",
      "Margin calc"
    ]
  },
  {
    "id": "043-live-insurance-fund-balance-usds-m-perpetual",
    "title": "Live Insurance Fund Balance (USDS-M Perpetual)",
    "url": "https://www.binance.com/en/futures/funding-history/perpetual/insurance-fund-history",
    "product": "USD-M Futures",
    "productArea": "Futures",
    "subcategory": "Live data",
    "section": "A. Futures Core / Liquidation, ADL, Insurance Fund",
    "pageType": "Data page",
    "source": "Live Data",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "insurance fund balance"
    ],
    "supportUseCases": [
      "Verification"
    ]
  },
  {
    "id": "009-live-trading-rules-leverage-margin",
    "title": "Live Trading Rules: Leverage & Margin",
    "url": "https://www.binance.com/en/futures/trading-rules/perpetual/leverage-margin",
    "product": "USD-M Futures",
    "productArea": "Futures",
    "subcategory": "Trading Rules",
    "section": "A. Futures Core / USDS-M Futures",
    "pageType": "Rules data",
    "source": "Live Data",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "per-symbol leverage tier",
      "MMR"
    ],
    "supportUseCases": [
      "Tier lookup"
    ]
  },
  {
    "id": "010-live-trading-rules-multi-asset-info-haircut",
    "title": "Live Trading Rules: Multi-Asset Info / Haircut",
    "url": "https://www.binance.com/en/futures/trading-rules/perpetual/multi-asset-info",
    "product": "USD-M Futures",
    "productArea": "Futures",
    "subcategory": "Trading Rules",
    "section": "A. Futures Core / USDS-M Futures",
    "pageType": "Rules data",
    "source": "Live Data",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "multi-assets haircut",
      "auto-exchange"
    ],
    "supportUseCases": [
      "Margin policy"
    ]
  },
  {
    "id": "001-usds-margined-futures-contract-specifications",
    "title": "USDS-Margined Futures Contract Specifications",
    "url": "https://www.binance.com/en/support/faq/usd%E2%93%A2-margined-futures-contract-specifications-360033161972",
    "product": "USD-M Futures",
    "productArea": "USDS-M",
    "subcategory": "Specifications",
    "section": "A. Futures Core / USDS-M Futures",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "linear",
      "perpetual",
      "quarterly",
      "8h funding",
      "minimum notional 5 USDT"
    ],
    "supportUseCases": [
      "Spec lookup"
    ]
  },
  {
    "id": "005-what-are-mark-price-and-price-index-in-usds-margined-futures",
    "title": "What Are Mark Price and Price Index in USDS-Margined Futures",
    "url": "https://www.binance.com/en/support/faq/what-are-mark-price-and-price-index-in-usd%E2%93%A2-margined-futures-360033525071",
    "product": "USD-M Futures",
    "productArea": "USDS-M",
    "subcategory": "Mark/Index Price",
    "section": "A. Futures Core / USDS-M Futures",
    "pageType": "FAQ",
    "source": "FAQ Index",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [
      "weighted average exchanges",
      "Median formula",
      "2.5-min MA",
      "Last Price Protected",
      "5% deviation safeguard"
    ],
    "supportUseCases": [
      "Mark/index price formula questions"
    ]
  },
  {
    "id": "002-what-are-usds-margined-and-coin-margined-futures",
    "title": "What Are USDS-Margined and COIN-Margined Futures?",
    "url": "https://www.binance.com/en/support/faq/what-are-usd%E2%93%A2-margined-futures-and-coin-margined-futures-85eac2bba0b342819122dc9bd4745e9b",
    "product": "USD-M Futures",
    "productArea": "USD-M Futures",
    "subcategory": "USDS-M Futures",
    "section": "A. Futures Core / USDS-M Futures",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P0",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "003-btc-margined-futures-contract-specifications",
    "title": "BTC-Margined Futures Contract Specifications",
    "url": "https://www.binance.com/en/support/faq/btc-margined-futures-contract-specifications-b961259540e047548d3b1b6f0cf017c0",
    "product": "USD-M Futures",
    "productArea": "USD-M Futures",
    "subcategory": "USDS-M Futures",
    "section": "A. Futures Core / USDS-M Futures",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "006-mark-price-in-usds-margined-quarterly-futures",
    "title": "Mark Price in USDS-Margined Quarterly Futures",
    "url": "https://www.binance.com/en/support/faq/mark-price-in-usd%E2%93%A2-margined-quarterly-futures-e9b19c16189249c7902c1457e24a36f8",
    "product": "USD-M Futures",
    "productArea": "USD-M Futures",
    "subcategory": "USDS-M Futures",
    "section": "A. Futures Core / USDS-M Futures",
    "pageType": "FAQ (formulas)",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "004-usdt-margined-quarterly-contract-spec-rules",
    "title": "USDT-Margined Quarterly Contract Spec & Rules",
    "url": "https://www.binance.com/en/support/faq/usdt-margined-quarterly-contract-specification-and-trading-rules-3ae441db4ae740e19af3fe9228eb6619",
    "product": "USD-M Futures",
    "productArea": "USD-M Futures",
    "subcategory": "USDS-M Futures",
    "section": "A. Futures Core / USDS-M Futures",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P1",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  },
  {
    "id": "073-easy-trade-mode-usds-m",
    "title": "Easy Trade Mode (USDS-M)",
    "url": "https://www.binance.com/en/support/faq/how-to-use-usd%E2%93%A2-m-lite-trading-mode-on-binance-futures-2f6b74f0f94c4837b147dc727847c291",
    "product": "USD-M Futures",
    "productArea": "USD-M Futures",
    "subcategory": "How-tos",
    "section": "A. Futures Core / Interface / Tools / How-tos",
    "pageType": "FAQ",
    "source": "FAQ",
    "priority": "P2",
    "confidence": "high",
    "keyTopics": [],
    "supportUseCases": []
  }
];
